---
- hosts: all
  tasks:
    - name: downloading docker script from https://get.docker.com/
      get_url:
        url: https://get.docker.com/
        dest: /tmp/docker.sh
        mode: '0777'
    - name: run docker script
      command: sh /tmp/docker.sh

          