---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      tags: install_nginx
    - name: start nginx
      service:
          name: nginx
          state: started
      tags: start_nginx
    - name: stop nginx
      service:
          name: nginx
          state: stopped
      tags: stop_nginx
    - name: ensure nginx is not installed
      apt: name=nginx state=absent
      tags: uninstall_nginx
 